{% set version = "0.10.1" %}

package:
  name: seaborn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/seaborn/seaborn-{{ version }}.tar.gz
  sha256: 2d1a0c9d6bd1bc3cadb0364b8f06540f51322a670cf8438d0fde1c1c7317adc0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.13.3
    - matplotlib-base >=2.1.2
    - scipy >=1.0.1
    - pandas >=0.22.0

test:
  imports:
    - seaborn
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://seaborn.pydata.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Statistical data visualization
  description: |
    Seaborn is a Python visualization library based on matplotlib. It
    provides a high-level interface for drawing attractive statistical graphics.
  doc_url: https://seaborn.pydata.org
  dev_url: https://github.com/mwaskom/seaborn

extra:
  recipe-maintainers:
    - msarahan
    - r-jain1
    - croth1
