{% set version = "0.12.0" %}

package:
  name: seaborn-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/seaborn/seaborn-{{ version }}.tar.gz
  sha256: 893f17292d8baca616c1578ddb58eb25c72d622f54fc5ee329c8207dc9b57b23

build:
  number: 0
  noarch: python

test:
  imports:
    - seaborn
  requires:
    - pip
  commands:
    - pip check

outputs:
  - name: seaborn-base
    build:
      noarch: python
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        - numpy >=1.15
        - matplotlib-base >=3.1
        - scipy >=1.3
        - pandas >=0.25
      test:
        imports:
          - seaborn

  - name: seaborn
    build:
      noarch: python
    requirements:
      run:
        - statsmodels >=0.10
        - {{ pin_subpackage('seaborn-base', max_pin="x.x.x.x") }}

about:
  home: https://seaborn.pydata.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Statistical data visualization
  description: |
    Seaborn is a Python visualization library based on matplotlib. It
    provides a high-level interface for drawing attractive statistical graphics.
  doc_url: https://seaborn.pydata.org
  dev_url: https://github.com/mwaskom/seaborn

extra:
  feedstock-name: seaborn
  recipe-maintainers:
    - msarahan
    - r-jain1
    - croth1
