{% set version = "0.11.1" %}

package:
  name: seaborn-base
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/seaborn/seaborn-{{ version }}.tar.gz
  sha256: 44e78eaed937c5a87fc7a892c329a7cc091060b67ebd1d0d306b446a74ba01ad

build:
  number: 1
  noarch: python

test:
  imports:
    - seaborn
  requires:
    - pip
  commands:
    - pip check

outputs:
  - name: seaborn-base
    build:
      noarch: python
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - numpy >=1.15
        - matplotlib-base >=2.2
        - scipy >=1.0.1
        - pandas >=0.23
      test:
        imports:
          - seaborn

  - name: seaborn
    build:
      noarch: python
    requirements:
      run:
        - statsmodels >=0.8.0
        - {{ pin_subpackage('seaborn-base', max_pin="x.x.x.x") }}

about:
  home: https://seaborn.pydata.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Statistical data visualization
  description: |
    Seaborn is a Python visualization library based on matplotlib. It
    provides a high-level interface for drawing attractive statistical graphics.
  doc_url: https://seaborn.pydata.org
  dev_url: https://github.com/mwaskom/seaborn

extra:
  recipe-maintainers:
    - msarahan
    - r-jain1
    - croth1
